/* This file is automatically generated with "make include/build_env.h". DO NOT EDIT */

#ifndef _BUILD_ENV_H
#define _BUILD_ENV_H

#define BUILD_ENV_UNAME "Linux ubuntu 4.15.0-34-generic #37~16.04.1-Ubuntu SMP Tue Aug 28 10:43:57 UTC 2018 i686 i686 i686 GNU/Linux"
#define BUILD_ENV_DATE "Mon Oct 22 00:41:44 PDT 2018"
#define BUILD_ENV_SRCDIR "/home/ubuntu/chenwei/padavan/padavan-fw/trunk/user/samba3/source"
#define BUILD_ENV_BUILDDIR "/home/ubuntu/chenwei/padavan/padavan-fw/trunk/user/samba3/source"
#define BUILD_ENV_USER "root"
#define BUILD_ENV_HOST "ubuntu"
#define BUILD_ENV_COMPILER "/home/ubuntu/chenwei/padavan/padavan-fw/trunk/../toolchain/out/bin/mipsel-linux-uclibc-gcc"
#endif /* _BUILD_ENV_H */
